# Generated by Django 5.0.2 on 2024-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlocation',
            name='category',
            field=models.CharField(choices=[('Living Room', 'Living Room'), ('Dining Room', 'Dining Room'), ('Hallway', 'Hallway'), ('Garden', 'Garden'), ('Office', 'Office'), ('Bathroom', 'Bathroom'), ('Bed Room', 'Bed room'), ('Kitchen', 'Kitchen'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
