# Generated by Django 5.0.2 on 2024-03-12 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=100)),
                ('type_of_device', models.TextField(max_length=100)),
                ('model', models.TextField(blank=True, max_length=100, null=True)),
                ('data_source_id', models.TextField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.sensorlocation')),
            ],
        ),
    ]
